sylius_grid:
    templates:
        action:
            export: '@SyliusGridImportExport\admin\import_export\grid\action\export.html.twig'
        bulk_action:
            export: '@SyliusGridImportExport\admin\import_export\grid\bulk_action\export.html.twig'

    grids:
        sylius_grid_import_export_admin_process:
            driver:
                name: doctrine/orm
                options:
                    class: Sylius\GridImportExport\Entity\Process
            sorting:
                createdAt: desc
            fields:
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                type:
                    type: twig
                    label: sylius.ui.type
                    options:
                        template: '@SyliusGridImportExport\admin\import_export\grid\field\type.html.twig'
                resource:
                    type: string
                    label: sylius.ui.resource
                status:
                    type: twig
                    label: sylius.ui.status
                    options:
                        template: '@SyliusGridImportExport\admin\import_export\grid\field\status.html.twig'
            actions:
                item:
                    show:
                        type: show
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
